// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CheckNCEIOrder(arg1) {
  return window['go']['main']['App']['CheckNCEIOrder'](arg1);
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function ExportBundle(arg1) {
  return window['go']['main']['App']['ExportBundle'](arg1);
}

export function ExportPNG(arg1) {
  return window['go']['main']['App']['ExportPNG'](arg1);
}

export function ExportText(arg1) {
  return window['go']['main']['App']['ExportText'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportBundle() {
  return window['go']['main']['App']['ImportBundle']();
}

export function ImportModel() {
  return window['go']['main']['App']['ImportModel']();
}

export function LoadDemoScenario() {
  return window['go']['main']['App']['LoadDemoScenario']();
}

export function LoadEphemeris(arg1) {
  return window['go']['main']['App']['LoadEphemeris'](arg1);
}

export function LoadForecasts(arg1) {
  return window['go']['main']['App']['LoadForecasts'](arg1);
}

export function LoadTelemetry(arg1) {
  return window['go']['main']['App']['LoadTelemetry'](arg1);
}

export function PreviewNCEIArchive(arg1) {
  return window['go']['main']['App']['PreviewNCEIArchive'](arg1);
}

export function RefreshLive() {
  return window['go']['main']['App']['RefreshLive']();
}

export function RequestNCEIArchive(arg1) {
  return window['go']['main']['App']['RequestNCEIArchive'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchEvents(arg1) {
  return window['go']['main']['App']['SearchEvents'](arg1);
}
