// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Bootstrap():Promise<domain.BootstrapDTO>;

export function CheckNCEIOrder(arg1:number):Promise<domain.NCEIOrderStatus>;

export function ClearCache():Promise<void>;

export function ExportBundle(arg1:domain.ExportBundle):Promise<string>;

export function ExportPNG(arg1:string):Promise<string>;

export function ExportText(arg1:domain.ExportBundle):Promise<string>;

export function GetSettings():Promise<domain.SettingsDTO>;

export function ImportBundle():Promise<domain.ExportBundle>;

export function ImportModel():Promise<domain.ModelImportSummary>;

export function LoadDemoScenario():Promise<domain.DemoScenarioDTO>;

export function LoadEphemeris(arg1:domain.TimeRange):Promise<domain.EphemerisResult>;

export function LoadForecasts(arg1:domain.TimeRange):Promise<domain.ForecastResult>;

export function LoadTelemetry(arg1:domain.TelemetryQuery):Promise<domain.TelemetrySeriesDTO>;

export function PreviewNCEIArchive(arg1:domain.NCEIArchiveQuery):Promise<domain.NCEIArchivePreview>;

export function RefreshLive():Promise<domain.LiveSnapshotDTO>;

export function RequestNCEIArchive(arg1:domain.NCEIArchiveRequest):Promise<domain.NCEIOrderStatus>;

export function SaveSettings(arg1:domain.SettingsUpdate):Promise<domain.SettingsDTO>;

export function SearchEvents(arg1:domain.EventQuery):Promise<domain.EventSearchResult>;
